name: Backend tests
on: [push]
jobs:
  build-and-test:
    name: Install dependencies, lint, and run backend tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run backend tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd):$(./tests/backend)
        python -m unittest discover tests
